sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install: 
  - pip install -q -r requirements.txt
  - pip install -q codecov pytest-cov
script: pytest --cov=messenger_bot --cov=quiz
after_success:
  - bash <(curl -s https://codecov.io/bash)
