source 'https://rubygems.org'

group :development, :test do
  gem 'puppet-lint', :require => false
  gem 'yaml-lint', :require => false
end

gem 'hiera-eyaml', :require => false
gem 'librarian-puppet', :require => false
gem 'puppet', :require => false
