# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('external_id', models.IntegerField(unique=True)),
                ('promisor_name', models.CharField(max_length=255)),
                ('parliament_period_name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('fulfilled', 'Fulfilled'), ('broken', 'Broken'), ('not_yet', 'Not Yet')], default='', max_length=255)),
                ('testable', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promises', to='quiz.Category')),
                ('parties', models.ManyToManyField(blank=True, related_name='promises', to='quiz.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
