# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manuscript',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic'), ('quiz', 'Quiz'), ('voter_guide', 'Voter guide')], default='generic', max_length=100),
        ),
        migrations.AddField(
            model_name='promise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick reply'), ('url', 'URL'), ('quiz_result', 'Quiz result'), ('quiz_q_promises_checked', 'Quiz checked promises'), ('quiz_q_party_select', 'Quiz which party promised'), ('quiz_q_party_bool', 'Quiz party promised yes or no'), ('vg_result', 'Voter guide result'), ('vg_categories', 'Voter guide category select'), ('vg_questions', 'Voter guide questions')], default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='promisereference',
            name='promise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='quiz.Promise'),
        ),
    ]
