# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170604_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscriptitem',
            name='action',
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_items', to='quiz.Manuscript'),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick reply'), ('url', 'URL'), ('quiz_result', 'Quiz: Show result'), ('quiz_q_promises_checked', 'Quiz: Show checked promises quesions'), ('quiz_q_party_select', 'Quiz: Show which party promised questions'), ('quiz_q_party_bool', 'Quiz: Show did party x promise y questions'), ('vg_result', 'Voter guide: Show result'), ('vg_categories', 'Voter guide: Show category select'), ('vg_questions', 'Voter guide: Show questions')], default='text', max_length=100),
        ),
    ]
