# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_interim_manuscript_manuscriptitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscriptitem',
            name='interim',
        ),
        migrations.RemoveField(
            model_name='manuscriptitem',
            name='promise',
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='promises',
            field=models.ManyToManyField(blank=True, to='quiz.Promise'),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
