# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170604_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscriptitem',
            old_name='button_text',
            new_name='reply_text_1',
        ),
        migrations.RemoveField(
            model_name='manuscriptitem',
            name='link',
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='reply_action_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_1_items', to='quiz.Manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='reply_action_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_2_items', to='quiz.Manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='reply_action_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_3_items', to='quiz.Manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='reply_text_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manuscriptitem',
            name='reply_text_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
