# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170607_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'HdoCategories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='promise',
            name='hdo_categories',
            field=models.ManyToManyField(blank=True, related_name='promises', to='quiz.HdoCategory'),
        ),
    ]
