# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170211_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptimage',
            name='type',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('broken', 'Broken'), ('not_yet', 'Not Yet'), ('partial', 'Partial')], default='fulfilled', max_length=100),
        ),
    ]
