# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170610_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterGuideAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hdocategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'HDO Categories'},
        ),
        migrations.AddField(
            model_name='manuscript',
            name='hdo_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.HdoCategory'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Category'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Used both for admin display and user display when tyoe=voting guide', max_length=255),
        ),
        migrations.AddField(
            model_name='voterguidealternative',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Manuscript'),
        ),
        migrations.AddField(
            model_name='voterguidealternative',
            name='promises',
            field=models.ManyToManyField(blank=True, to='quiz.Promise'),
        ),
    ]
