# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_manuscriptimage_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interim',
        ),
    ]
