# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170627_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingGuideAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_guide_answers', to='quiz.AnswerSet')),
                ('voting_guide_alternative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.VoterGuideAlternative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
