# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20170711_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterguidealternative',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_guide_alternatives', to='quiz.Manuscript'),
        ),
    ]
