# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20170714_1337'),
        ('quiz', '0011_auto_20170715_1554'),
    ]

    operations = [
    ]
