# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0001_initial'),
        ('quiz', '0011_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.ChatSession'),
        ),
    ]
