# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_answer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, choices=[('agree', 'Agrees'), ('disagree', 'Diagrees')], default='', help_text='Used with election-o-matic-3000', max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(blank=True, choices=[('fulfilled', 'Fulfilled'), ('broken', 'Broken'), ('not_yet', 'Not Yet'), ('partial', 'Partial')], default='', help_text='Used with kept/broken quiz', max_length=255),
        ),
    ]
