# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20170325_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='collection',
            new_name='answer_set',
        ),
    ]
