# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20170716_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterGuideAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_guide_answers', to='quiz.AnswerSet')),
                ('voter_guide_alternative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.VoterGuideAlternative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='votingguideanswer',
            name='answer_set',
        ),
        migrations.RemoveField(
            model_name='votingguideanswer',
            name='voting_guide_alternative',
        ),
        migrations.AddField(
            model_name='hdocategory',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Quick reply labels', max_length=255),
        ),
        migrations.DeleteModel(
            name='VotingGuideAnswer',
        ),
    ]
