# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20170807_1743'),
        ('quiz', '0016_auto_20170725_0017'),
    ]

    operations = [
    ]
