# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0001_initial'),
        ('quiz', '0016_auto_20170415_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='session',
        ),
        migrations.AddField(
            model_name='answerset',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.ChatSession'),
        ),
    ]
