# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20170415_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.AnswerSet'),
        ),
    ]
