# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_merge_20170807_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='short_tile',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
