# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_merge_20170807_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguidealternative',
            name='no_answer',
            field=models.BooleanField(default=False),
        ),
    ]
