# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_party_short_tile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='short_tile',
            new_name='short_title',
        ),
    ]
