# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20170815_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('correct_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quiz.AnswerSet')),
                ('quiz_alternative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz.QuizAlternative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='is_first_in_category',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=100),
        ),
        migrations.AddField(
            model_name='quizalternative',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_alternatives', to='quiz.Manuscript'),
        ),
        migrations.AddField(
            model_name='quizalternative',
            name='promise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Promise'),
        ),
        migrations.AlterUniqueTogether(
            name='quizalternative',
            unique_together=set([('text', 'manuscript')]),
        ),
    ]
