# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20170415_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='messenger_bot.ChatSession'),
        ),
    ]
