# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20170904_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizalternative',
            name='promise',
        ),
        migrations.AddField(
            model_name='quizalternative',
            name='promises',
            field=models.ManyToManyField(blank=True, to='quiz.Promise'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='default',
            field=models.CharField(choices=[('default', 'Default'), ('default_vg', 'Voter guide'), ('default_quiz', 'Quiz'), ('none', 'None')], default='none', max_length=254),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick reply'), ('url', 'URL'), ('quiz_result', 'Quiz: Show result'), ('quiz_q_promises_checked', 'Quiz: Show checked promise questions'), ('quiz_q_party_select', 'Quiz: Show which party promised what questions'), ('quiz_q_party_bool', 'Quiz: Show did party x promise y questions'), ('quiz_categories', 'Quiz: Show category select'), ('vg_result', 'Voter guide: Show result'), ('vg_categories', 'Voter guide: Show category select'), ('vg_questions', 'Voter guide: Show questions')], default='text', max_length=100),
        ),
    ]
