# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20170904_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='level',
            field=models.CharField(choices=[('low', 'Nybegynner'), ('medium', 'Middels'), ('high', 'Politisk NØRD')], default='medium', max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Used both for admin display and user display when type=voting guide or type=quiz', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quick_reply', 'Quick reply'), ('url', 'URL'), ('quiz_result', 'Quiz: Show result'), ('quiz_q_promises_checked', 'Quiz: Show checked promise questions'), ('quiz_q_party_select', 'Quiz: Show which party promised what questions'), ('quiz_q_party_bool', 'Quiz: Show did party x promise y questions'), ('quiz_level', 'Quiz: Show level select'), ('quiz_categories', 'Quiz: Show category select'), ('quiz_question', 'Quiz: Show question'), ('vg_result', 'Voter guide: Show result'), ('vg_categories', 'Voter guide: Show category select'), ('vg_questions', 'Voter guide: Show questions')], default='text', max_length=100),
        ),
    ]
