# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20170904_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizalternative',
            name='text',
            field=models.TextField(),
        ),
    ]
