# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 22:24
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    QuizAnswer = apps.get_model('quiz', 'QuizAnswer')
    for row in QuizAnswer.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_quizanswer_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
