# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20170906_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
