# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20170906_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
