# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20171022_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptitem',
            name='reply_action_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_1_items', to='quiz.Manuscript'),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='reply_action_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_2_items', to='quiz.Manuscript'),
        ),
        migrations.AlterField(
            model_name='manuscriptitem',
            name='reply_action_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_3_items', to='quiz.Manuscript'),
        ),
    ]
