# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='state',
            field=models.CharField(choices=[('in_progress', 'In progress')], default='in_progress', max_length=100),
        ),
    ]
